### PR TITLE
Add mysql2 adapter

### PR DESCRIPTION
**Pull request by svegaca**
I've just added an adapter compatible with MySQL. Iin fact, is a copy of PostgreSQL adapter, so maybe could be interesting use PostgreeSQL adapter for all database types compatibles with it. But well, I think maybe can be better for now keep each database type with his own adapter.

It works for me, I hope you find it useful.

### CODE REVIEW

**Comment by westonganger** [comment]
+1

**Comment by lucasprag** [comment]
+1

**Comment by lucasprag** [comment]
ping @joekur @kiurchv

**Comment by ebenoist** [comment]
Thanks for pinging this and sorry its taken so long to get a response here. We'll make sure this gets looked at today! Thank you so much for staying on top of this despite the radio silence.

**Comment by lucasprag** [comment]
Thank you @ebenoist. I'm studying this gem in order to validate uniqueness using a mysql index to avoid a race condition that I got. =)

**Comment by ebenoist** [comment]
No problem, sorry it got lost in the shuffle. Thank you @svegaca for putting this up!

**Comment by ebenoist** [comment]
Everything here checks out. Merging! Thanks again for the contribution.

**Comment by ebenoist** [comment]
@lucasprag @westonganger @svegaca The new version with this change has been pushed as 1.3.0 to rubygems: https://rubygems.org/gems/rescue_unique_constraint/versions/1.3.0

**Comment by lucasprag** [comment]
Awesome! Thank you very much =) @ebenoist

**Pull request merged**
