### PR TITLE
Expands the range of allowed ActiveRecord version to include Rails 6

### PR DESCRIPTION
**Pull request by bombino**

### CODE REVIEW

**Comment by GSmes** [comment]
👍 🙏

**Comment by kylecrum** [comment]
@mcostanza do you want to take a look?

**Comment by mcostanza** [comment]
Looks good, thanks for the update!

**Comment by mcostanza** [comment]
@bombino a new gem version with your change has been published: https://rubygems.org/gems/rescue_unique_constraint/versions/1.6.0

**Pull request merged**
