### PR TITLE
chore(*): Allow Rails 7

### PR DESCRIPTION
**Pull request by plribeiro3000**

### CODE REVIEW

**Comment by adaddeo** [comment]
Possible the merge this?

**Comment by plribeiro3000** [comment]
@adaddeo As a workaround i did a release with just this change in a new gem `https://rubygems.org/gems/rescue_unique_constraint-p`.

Check it out if you need to fix this fast.

**Comment by meshulam** [comment]
This has been fixed via #19. Thanks!

**Comment by plribeiro3000** [comment]
Awesome @meshulam !

I hope the project gets actively maintained again since it is something that no other gem does. At least i could not find!

**Pull request closed without merging**
